apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: tax-calculator-pipeline-run-
spec:
  pipelineRef:
    name: tax-calculator-pipeline
  params:
    - name: repo-url
      value: "https://github.com/armalik4640-debug/Tax-Calculator-app.git"
    - name: revision
      value: "main"
    - name: image-name
      value: "us.icr.io/calculator-app/tax-calculator:2"
  workspaces:
    - name: pipeline-workspace
      persistentVolumeClaim:
        claimName: tax-calculator-pvc
